name: SageMaker Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Set the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project dependencies

      - name: Set up AWS CLI
        run: |
          pip install awscli  # Install AWS CLI to interact with SageMaker
          aws --version  # Confirm AWS CLI is installed

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-2  

      - name: Deploy to SageMaker
        run: |
          python AnsweringChatbot.ipynb  
          
      - name: Output SageMaker Endpoint URL
        run: |
          echo "SageMaker Endpoint URL: https://runtime.sagemaker.us-east-2.amazonaws.com/endpoints/${{ steps.deploy.outputs.endpoint_name }}/invocations"
